---

# Travis file for cookiecutter ansible role template

language: python

python:
  - '3.7'

env:
  - ANSIBLE_ROLES_PATH=${TRAVIS_BUILD_DIR%/*/*}

install:
  # Install python pytest plugin to cookiecutter template testing
  - pip install -r requirements.txt

script:
  # Run tests
  - tox
